var list4 = [
    {
      cue: "Mehl",
      target: "Reis",
      cond: "SEM",
      cue_image: "img/Mehl4.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/MehlTS.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hammer",
      target: "Suppe",
      cond: "NONE",
      cue_image: "img/Hammer4.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/HammerTS.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Topf",
      target: "Knopf",
      cond: "PHON",
      cue_image: "img/Topf3.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/TopfTC.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Flugzeug",
      target: "Flugzeug",
      cond: "IDEN",
      cue_image: "img/Flugzeug4.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/FlugzeugTS.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Strassenbahn",
      target: "Strassenbahn",
      cond: "IDEN",
      cue_image: "img/Strassenbahn3.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/StrassenbahnTC.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bein",
      target: "Wein",
      cond: "PHON",
      cue_image: "img/Bein3.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/BeinTC.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fahrrad",
      target: "Hose",
      cond: "NONE",
      cue_image: "img/Fahrrad3.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/FahrradTC.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bauch",
      target: "Lauch",
      cond: "PHON",
      cue_image: "img/Bauch4.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/BauchTS.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Wachs",
      target: "Dachs",
      cond: "PHON",
      cue_image: "img/Wachs4.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/WachsTS.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schuh",
      target: "Schuh",
      cond: "IDEN",
      cue_image: "img/Schuh3.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/SchuhTC.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Loeffel",
      target: "Tasche",
      cond: "NONE",
      cue_image: "img/Loeffel4.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/LoeffelTS.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pelikan",
      target: "Kartoffel",
      cond: "NONE",
      cue_image: "img/Pelikan3.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/PelikanTC.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Huhn",
      target: "Strassenbahn",
      cond: "NONE",
      cue_image: "img/Huhn4.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/HuhnTS.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pfanne",
      target: "Schwein",
      cond: "NONE",
      cue_image: "img/Pfanne3.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/PfanneTC.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Anzug",
      target: "Hose",
      cond: "SEM",
      cue_image: "img/Anzug4.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/AnzugTS.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Milch",
      target: "Kaffee",
      cond: "SEM",
      cue_image: "img/Milch3.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/MilchTC.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fisch",
      target: "Fisch",
      cond: "IDEN",
      cue_image: "img/Fisch4.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/FischTS.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schiff",
      target: "Lauch",
      cond: "NONE",
      cue_image: "img/Schiff4.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/SchiffTS.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Flasche",
      target: "Tasche",
      cond: "PHON",
      cue_image: "img/Flasche4.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/FlascheTS.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kamm",
      target: "Dachs",
      cond: "NONE",
      cue_image: "img/Kamm4.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/KammTS.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Strassenbahn",
      target: "Strassenbahn",
      cond: "IDEN",
      cue_image: "img/Strassenbahn4.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/StrassenbahnTS.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Rakete",
      target: "Rakete",
      cond: "IDEN",
      cue_image: "img/Rakete4.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/RaketeTS.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Topf",
      target: "Knopf",
      cond: "PHON",
      cue_image: "img/Topf4.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/TopfTS.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zahn",
      target: "Pferd",
      cond: "NONE",
      cue_image: "img/Zahn4.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/ZahnTS.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Brot",
      target: "Fisch",
      cond: "NONE",
      cue_image: "img/Brot4.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/BrotTS.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Lauch",
      target: "Lauch",
      cond: "IDEN",
      cue_image: "img/Lauch4.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/LauchTS.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tasche",
      target: "Tasche",
      cond: "IDEN",
      cue_image: "img/Tasche4.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/TascheTS.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Dachs",
      target: "Dachs",
      cond: "IDEN",
      cue_image: "img/Dachs4.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/DachsTS.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Otter",
      target: "Wal",
      cond: "SEM",
      cue_image: "img/Otter3.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/OtterTC.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schraube",
      target: "Traube",
      cond: "PHON",
      cue_image: "img/Schraube4.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/SchraubeTS.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tee",
      target: "Tee",
      cond: "IDEN",
      cue_image: "img/Tee4.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/TeeTS.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pfanne",
      target: "Schwein",
      cond: "NONE",
      cue_image: "img/Pfanne4.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/PfanneTS.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tisch",
      target: "Fisch",
      cond: "PHON",
      cue_image: "img/Tisch4.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/TischTS.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwert",
      target: "Pferd",
      cond: "PHON",
      cue_image: "img/Schwert4.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/SchwertTS.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Stiefel",
      target: "Tasche",
      cond: "SEM",
      cue_image: "img/Stiefel1.jpg",
      target_image: "img/Tasche1.jpg",
      cue_word: "img/StiefelCC.jpg",
      target_word: "img/TascheCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Milch",
      target: "Kaffee",
      cond: "SEM",
      cue_image: "img/Milch4.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/MilchTS.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pedal",
      target: "Wal",
      cond: "PHON",
      cue_image: "img/Pedal4.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/PedalTS.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bauch",
      target: "Lauch",
      cond: "PHON",
      cue_image: "img/Bauch1.jpg",
      target_image: "img/Lauch1.jpg",
      cue_word: "img/BauchCC.jpg",
      target_word: "img/LauchCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bier",
      target: "Tee",
      cond: "SEM",
      cue_image: "img/Bier4.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/BierTS.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tapete",
      target: "Rakete",
      cond: "PHON",
      cue_image: "img/Tapete4.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/TapeteTS.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fisch",
      target: "Fisch",
      cond: "IDEN",
      cue_image: "img/Fisch1.jpg",
      target_image: "img/Fisch1.jpg",
      cue_word: "img/FischCC.jpg",
      target_word: "img/FischCC.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schuh",
      target: "Schuh",
      cond: "IDEN",
      cue_image: "img/Schuh4.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/SchuhTS.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Loeffel",
      target: "Tasche",
      cond: "NONE",
      cue_image: "img/Loeffel1.jpg",
      target_image: "img/Tasche2.jpg",
      cue_word: "img/LoeffelCC.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Dachs",
      target: "Dachs",
      cond: "IDEN",
      cue_image: "img/Dachs1.jpg",
      target_image: "img/Dachs1.jpg",
      cue_word: "img/DachsCC.jpg",
      target_word: "img/DachsCC.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Apfel",
      target: "Traube",
      cond: "SEM",
      cue_image: "img/Apfel4.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/ApfelTS.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Reis",
      target: "Reis",
      cond: "IDEN",
      cue_image: "img/Reis4.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/ReisTS.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fahrrad",
      target: "Hose",
      cond: "NONE",
      cue_image: "img/Fahrrad4.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/FahrradTS.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Klee",
      target: "Tee",
      cond: "PHON",
      cue_image: "img/Klee4.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/KleeTS.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pelikan",
      target: "Kartoffel",
      cond: "NONE",
      cue_image: "img/Pelikan4.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/PelikanTS.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Nest",
      target: "Schuh",
      cond: "NONE",
      cue_image: "img/Nest4.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/NestTS.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Saft",
      target: "Wein",
      cond: "SEM",
      cue_image: "img/Saft4.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/SaftTS.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Wachs",
      target: "Dachs",
      cond: "PHON",
      cue_image: "img/Wachs1.jpg",
      target_image: "img/Dachs2.jpg",
      cue_word: "img/WachsCC.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Traube",
      target: "Traube",
      cond: "IDEN",
      cue_image: "img/Traube4.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/TraubeTS.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Ballon",
      target: "Flugzeug",
      cond: "SEM",
      cue_image: "img/Ballon4.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/BallonTS.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Huhn",
      target: "Strassenbahn",
      cond: "NONE",
      cue_image: "img/Huhn1.jpg",
      target_image: "img/Strassenbahn1.jpg",
      cue_word: "img/HuhnCC.jpg",
      target_word: "img/StrassenbahnCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hut",
      target: "Kaffee",
      cond: "NONE",
      cue_image: "img/Hut4.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/HutTS.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Klee",
      target: "Tee",
      cond: "PHON",
      cue_image: "img/Klee1.jpg",
      target_image: "img/Tee1.jpg",
      cue_word: "img/KleeCC.jpg",
      target_word: "img/TeeCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kleid",
      target: "Schuh",
      cond: "SEM",
      cue_image: "img/Kleid1.jpg",
      target_image: "img/Schuh1.jpg",
      cue_word: "img/KleidCC.jpg",
      target_word: "img/SchuhCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Otter",
      target: "Wal",
      cond: "SEM",
      cue_image: "img/Otter4.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/OtterTS.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zwiebel",
      target: "Suppe",
      cond: "SEM",
      cue_image: "img/Zwiebel4.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/ZwiebelTS.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schraube",
      target: "Traube",
      cond: "PHON",
      cue_image: "img/Schraube1.jpg",
      target_image: "img/Traube1.jpg",
      cue_word: "img/SchraubeCC.jpg",
      target_word: "img/TraubeCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bauch",
      target: "Lauch",
      cond: "PHON",
      cue_image: "img/Bauch2.jpg",
      target_image: "img/Lauch2.jpg",
      cue_word: "img/BauchCS.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Affe",
      target: "Flugzeug",
      cond: "NONE",
      cue_image: "img/Affe4.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/AffeTS.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Anzug",
      target: "Hose",
      cond: "SEM",
      cue_image: "img/Anzug1.jpg",
      target_image: "img/Hose1.jpg",
      cue_word: "img/AnzugCC.jpg",
      target_word: "img/HoseCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Klee",
      target: "Tee",
      cond: "PHON",
      cue_image: "img/Klee2.jpg",
      target_image: "img/Tee2.jpg",
      cue_word: "img/KleeCS.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hirsch",
      target: "Pferd",
      cond: "SEM",
      cue_image: "img/Hirsch4.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/HirschTS.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Otter",
      target: "Wal",
      cond: "SEM",
      cue_image: "img/Otter1.jpg",
      target_image: "img/Wal1.jpg",
      cue_word: "img/OtterCC.jpg",
      target_word: "img/WalCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Suppe",
      target: "Suppe",
      cond: "IDEN",
      cue_image: "img/Suppe4.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/SuppeTS.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Apfel",
      target: "Traube",
      cond: "SEM",
      cue_image: "img/Apfel1.jpg",
      target_image: "img/Traube2.jpg",
      cue_word: "img/ApfelCC.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tasche",
      target: "Tasche",
      cond: "IDEN",
      cue_image: "img/Tasche1.jpg",
      target_image: "img/Tasche3.jpg",
      cue_word: "img/TascheCC.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schornstein",
      target: "Schwein",
      cond: "PHON",
      cue_image: "img/Schornstein4.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/SchornsteinTS.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Brot",
      target: "Fisch",
      cond: "NONE",
      cue_image: "img/Brot1.jpg",
      target_image: "img/Fisch2.jpg",
      cue_word: "img/BrotCC.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schlagzeug",
      target: "Flugzeug",
      cond: "PHON",
      cue_image: "img/Schlagzeug1.jpg",
      target_image: "img/Flugzeug1.jpg",
      cue_word: "img/SchlagzeugCC.jpg",
      target_word: "img/FlugzeugCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwert",
      target: "Pferd",
      cond: "PHON",
      cue_image: "img/Schwert1.jpg",
      target_image: "img/Pferd1.jpg",
      cue_word: "img/SchwertCC.jpg",
      target_word: "img/PferdCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Gurke",
      target: "Wal",
      cond: "NONE",
      cue_image: "img/Gurke1.jpg",
      target_image: "img/Wal2.jpg",
      cue_word: "img/GurkeCC.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hammer",
      target: "Suppe",
      cond: "NONE",
      cue_image: "img/Hammer1.jpg",
      target_image: "img/Suppe1.jpg",
      cue_word: "img/HammerCC.jpg",
      target_word: "img/SuppeCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kleid",
      target: "Schuh",
      cond: "SEM",
      cue_image: "img/Kleid2.jpg",
      target_image: "img/Schuh2.jpg",
      cue_word: "img/KleidCS.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwan",
      target: "Strassenbahn",
      cond: "PHON",
      cue_image: "img/Schwan1.jpg",
      target_image: "img/Strassenbahn2.jpg",
      cue_word: "img/SchwanCC.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pfanne",
      target: "Schwein",
      cond: "NONE",
      cue_image: "img/Pfanne1.jpg",
      target_image: "img/Schwein1.jpg",
      cue_word: "img/PfanneCC.jpg",
      target_word: "img/SchweinCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hund",
      target: "Fisch",
      cond: "SEM",
      cue_image: "img/Hund1.jpg",
      target_image: "img/Fisch3.jpg",
      cue_word: "img/HundCC.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hemd",
      target: "Knopf",
      cond: "SEM",
      cue_image: "img/Hemd4.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/HemdTS.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bein",
      target: "Wein",
      cond: "PHON",
      cue_image: "img/Bein4.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/BeinTS.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Gurke",
      target: "Wal",
      cond: "NONE",
      cue_image: "img/Gurke2.jpg",
      target_image: "img/Wal3.jpg",
      cue_word: "img/GurkeCS.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hubschrauber",
      target: "Rakete",
      cond: "SEM",
      cue_image: "img/Hubschrauber4.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/HubschrauberTS.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Rose",
      target: "Hose",
      cond: "PHON",
      cue_image: "img/Rose1.jpg",
      target_image: "img/Hose2.jpg",
      cue_word: "img/RoseCC.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Strassenbahn",
      target: "Strassenbahn",
      cond: "IDEN",
      cue_image: "img/Strassenbahn1.jpg",
      target_image: "img/Strassenbahn3.jpg",
      cue_word: "img/StrassenbahnCC.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Lauch",
      target: "Lauch",
      cond: "IDEN",
      cue_image: "img/Lauch1.jpg",
      target_image: "img/Lauch3.jpg",
      cue_word: "img/LauchCC.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schuh",
      target: "Schuh",
      cond: "IDEN",
      cue_image: "img/Schuh1.jpg",
      target_image: "img/Schuh3.jpg",
      cue_word: "img/SchuhCC.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Puppe",
      target: "Suppe",
      cond: "PHON",
      cue_image: "img/Puppe1.jpg",
      target_image: "img/Suppe2.jpg",
      cue_word: "img/PuppeCC.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Wein",
      target: "Wein",
      cond: "IDEN",
      cue_image: "img/Wein1.jpg",
      target_image: "img/Wein1.jpg",
      cue_word: "img/WeinCC.jpg",
      target_word: "img/WeinCC.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Otter",
      target: "Wal",
      cond: "SEM",
      cue_image: "img/Otter2.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/OtterCS.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Ziege",
      target: "Schwein",
      cond: "SEM",
      cue_image: "img/Ziege1.jpg",
      target_image: "img/Schwein2.jpg",
      cue_word: "img/ZiegeCC.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Flasche",
      target: "Tasche",
      cond: "PHON",
      cue_image: "img/Flasche1.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/FlascheCC.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Topf",
      target: "Knopf",
      cond: "PHON",
      cue_image: "img/Topf1.jpg",
      target_image: "img/Knopf1.jpg",
      cue_word: "img/TopfCC.jpg",
      target_word: "img/KnopfCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kamm",
      target: "Dachs",
      cond: "NONE",
      cue_image: "img/Kamm1.jpg",
      target_image: "img/Dachs3.jpg",
      cue_word: "img/KammCC.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schiff",
      target: "Lauch",
      cond: "NONE",
      cue_image: "img/Schiff1.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/SchiffCC.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Puppe",
      target: "Suppe",
      cond: "PHON",
      cue_image: "img/Puppe2.jpg",
      target_image: "img/Suppe3.jpg",
      cue_word: "img/PuppeCS.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pantoffel",
      target: "Kartoffel",
      cond: "PHON",
      cue_image: "img/Pantoffel4.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/PantoffelTS.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pferd",
      target: "Pferd",
      cond: "IDEN",
      cue_image: "img/Pferd1.jpg",
      target_image: "img/Pferd2.jpg",
      cue_word: "img/PferdCC.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schornstein",
      target: "Schwein",
      cond: "PHON",
      cue_image: "img/Schornstein1.jpg",
      target_image: "img/Schwein3.jpg",
      cue_word: "img/SchornsteinCC.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tapete",
      target: "Rakete",
      cond: "PHON",
      cue_image: "img/Tapete1.jpg",
      target_image: "img/Rakete1.jpg",
      cue_word: "img/TapeteCC.jpg",
      target_word: "img/RaketeCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fahrrad",
      target: "Hose",
      cond: "NONE",
      cue_image: "img/Fahrrad1.jpg",
      target_image: "img/Hose3.jpg",
      cue_word: "img/FahrradCC.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tee",
      target: "Tee",
      cond: "IDEN",
      cue_image: "img/Tee1.jpg",
      target_image: "img/Tee3.jpg",
      cue_word: "img/TeeCC.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schnee",
      target: "Kaffee",
      cond: "PHON",
      cue_image: "img/Schnee1.jpg",
      target_image: "img/Kaffee1.jpg",
      cue_word: "img/SchneeCC.jpg",
      target_word: "img/KaffeeCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hammer",
      target: "Suppe",
      cond: "NONE",
      cue_image: "img/Hammer2.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/HammerCS.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Traube",
      target: "Traube",
      cond: "IDEN",
      cue_image: "img/Traube1.jpg",
      target_image: "img/Traube3.jpg",
      cue_word: "img/TraubeCC.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zahn",
      target: "Pferd",
      cond: "NONE",
      cue_image: "img/Zahn1.jpg",
      target_image: "img/Pferd3.jpg",
      cue_word: "img/ZahnCC.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwein",
      target: "Schwein",
      cond: "IDEN",
      cue_image: "img/Schwein1.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/SchweinCC.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Eis",
      target: "Reis",
      cond: "PHON",
      cue_image: "img/Eis4.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/EisTS.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Elefant",
      target: "Rakete",
      cond: "NONE",
      cue_image: "img/Elefant1.jpg",
      target_image: "img/Rakete2.jpg",
      cue_word: "img/ElefantCC.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zelt",
      target: "Wein",
      cond: "NONE",
      cue_image: "img/Zelt1.jpg",
      target_image: "img/Wein2.jpg",
      cue_word: "img/ZeltCC.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Milch",
      target: "Kaffee",
      cond: "SEM",
      cue_image: "img/Milch1.jpg",
      target_image: "img/Kaffee2.jpg",
      cue_word: "img/MilchCC.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Knopf",
      target: "Knopf",
      cond: "IDEN",
      cue_image: "img/Knopf1.jpg",
      target_image: "img/Knopf2.jpg",
      cue_word: "img/KnopfCC.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pedal",
      target: "Wal",
      cond: "PHON",
      cue_image: "img/Pedal1.jpg",
      target_image: "img/Wal5.jpg",
      cue_word: "img/PedalCC.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwert",
      target: "Pferd",
      cond: "PHON",
      cue_image: "img/Schwert2.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/SchwertCS.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Ballon",
      target: "Flugzeug",
      cond: "SEM",
      cue_image: "img/Ballon1.jpg",
      target_image: "img/Flugzeug2.jpg",
      cue_word: "img/BallonCC.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Horn",
      target: "Reis",
      cond: "NONE",
      cue_image: "img/Horn1.jpg",
      target_image: "img/Reis1.jpg",
      cue_word: "img/HornCC.jpg",
      target_word: "img/ReisCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Elefant",
      target: "Rakete",
      cond: "NONE",
      cue_image: "img/Elefant2.jpg",
      target_image: "img/Rakete3.jpg",
      cue_word: "img/ElefantCS.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tisch",
      target: "Fisch",
      cond: "PHON",
      cue_image: "img/Tisch1.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/TischCC.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pantoffel",
      target: "Kartoffel",
      cond: "PHON",
      cue_image: "img/Pantoffel1.jpg",
      target_image: "img/Kartoffel1.jpg",
      cue_word: "img/PantoffelCC.jpg",
      target_word: "img/KartoffelCC.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Gras",
      target: "Knopf",
      cond: "NONE",
      cue_image: "img/Gras1.jpg",
      target_image: "img/Knopf3.jpg",
      cue_word: "img/GrasCC.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Dachs",
      target: "Dachs",
      cond: "IDEN",
      cue_image: "img/Dachs2.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/DachsCS.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tee",
      target: "Tee",
      cond: "IDEN",
      cue_image: "img/Tee2.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/TeeCS.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Affe",
      target: "Flugzeug",
      cond: "NONE",
      cue_image: "img/Affe1.jpg",
      target_image: "img/Flugzeug3.jpg",
      cue_word: "img/AffeCC.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Horn",
      target: "Reis",
      cond: "NONE",
      cue_image: "img/Horn2.jpg",
      target_image: "img/Reis2.jpg",
      cue_word: "img/HornCS.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Wein",
      target: "Wein",
      cond: "IDEN",
      cue_image: "img/Wein2.jpg",
      target_image: "img/Wein3.jpg",
      cue_word: "img/WeinCS.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Rakete",
      target: "Rakete",
      cond: "IDEN",
      cue_image: "img/Rakete1.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/RaketeCC.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pelikan",
      target: "Kartoffel",
      cond: "NONE",
      cue_image: "img/Pelikan1.jpg",
      target_image: "img/Kartoffel2.jpg",
      cue_word: "img/PelikanCC.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwan",
      target: "Strassenbahn",
      cond: "PHON",
      cue_image: "img/Schwan2.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/SchwanCS.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schwein",
      target: "Schwein",
      cond: "IDEN",
      cue_image: "img/Schwein2.jpg",
      target_image: "img/Schwein5.jpg",
      cue_word: "img/SchweinCS.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bier",
      target: "Tee",
      cond: "SEM",
      cue_image: "img/Bier1.jpg",
      target_image: "img/Tee5.jpg",
      cue_word: "img/BierCC.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Flugzeug",
      target: "Flugzeug",
      cond: "IDEN",
      cue_image: "img/Flugzeug1.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/FlugzeugCC.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Reis",
      target: "Reis",
      cond: "IDEN",
      cue_image: "img/Reis1.jpg",
      target_image: "img/Reis3.jpg",
      cue_word: "img/ReisCC.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Fahrrad",
      target: "Hose",
      cond: "NONE",
      cue_image: "img/Fahrrad2.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/FahrradCS.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Topf",
      target: "Knopf",
      cond: "PHON",
      cue_image: "img/Topf2.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/TopfCS.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kartoffel",
      target: "Kartoffel",
      cond: "IDEN",
      cue_image: "img/Kartoffel1.jpg",
      target_image: "img/Kartoffel3.jpg",
      cue_word: "img/KartoffelCC.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Rakete",
      target: "Rakete",
      cond: "IDEN",
      cue_image: "img/Rakete2.jpg",
      target_image: "img/Rakete5.jpg",
      cue_word: "img/RaketeCS.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Traube",
      target: "Traube",
      cond: "IDEN",
      cue_image: "img/Traube2.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/TraubeCS.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tasche",
      target: "Tasche",
      cond: "IDEN",
      cue_image: "img/Tasche2.jpg",
      target_image: "img/Tasche5.jpg",
      cue_word: "img/TascheCS.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schlagzeug",
      target: "Flugzeug",
      cond: "PHON",
      cue_image: "img/Schlagzeug2.jpg",
      target_image: "img/Flugzeug5.jpg",
      cue_word: "img/SchlagzeugCS.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Mehl",
      target: "Reis",
      cond: "SEM",
      cue_image: "img/Mehl1.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/MehlCC.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kohl",
      target: "Lauch",
      cond: "SEM",
      cue_image: "img/Kohl1.jpg",
      target_image: "img/Lauch5.jpg",
      cue_word: "img/KohlCC.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schnee",
      target: "Kaffee",
      cond: "PHON",
      cue_image: "img/Schnee2.jpg",
      target_image: "img/Kaffee3.jpg",
      cue_word: "img/SchneeCS.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pelikan",
      target: "Kartoffel",
      cond: "NONE",
      cue_image: "img/Pelikan2.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/PelikanCS.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schuh",
      target: "Schuh",
      cond: "IDEN",
      cue_image: "img/Schuh2.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/SchuhCS.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Knopf",
      target: "Knopf",
      cond: "IDEN",
      cue_image: "img/Knopf2.jpg",
      target_image: "img/Knopf5.jpg",
      cue_word: "img/KnopfCS.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Saft",
      target: "Wein",
      cond: "SEM",
      cue_image: "img/Saft1.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/SaftCC.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zahn",
      target: "Pferd",
      cond: "NONE",
      cue_image: "img/Zahn2.jpg",
      target_image: "img/Pferd5.jpg",
      cue_word: "img/ZahnCS.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Reis",
      target: "Reis",
      cond: "IDEN",
      cue_image: "img/Reis2.jpg",
      target_image: "img/Reis5.jpg",
      cue_word: "img/ReisCS.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hose",
      target: "Hose",
      cond: "IDEN",
      cue_image: "img/Hose1.jpg",
      target_image: "img/Hose5.jpg",
      cue_word: "img/HoseCC.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kaffee",
      target: "Kaffee",
      cond: "IDEN",
      cue_image: "img/Kaffee1.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/KaffeeCC.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schnitzel",
      target: "Kartoffel",
      cond: "SEM",
      cue_image: "img/Schnitzel1.jpg",
      target_image: "img/Kartoffel5.jpg",
      cue_word: "img/SchnitzelCC.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kuh",
      target: "Schuh",
      cond: "PHON",
      cue_image: "img/Kuh1.jpg",
      target_image: "img/Schuh5.jpg",
      cue_word: "img/KuhCC.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Tisch",
      target: "Fisch",
      cond: "PHON",
      cue_image: "img/Tisch2.jpg",
      target_image: "img/Fisch5.jpg",
      cue_word: "img/TischCS.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Saft",
      target: "Wein",
      cond: "SEM",
      cue_image: "img/Saft2.jpg",
      target_image: "img/Wein5.jpg",
      cue_word: "img/SaftCS.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Baer",
      target: "Dachs",
      cond: "SEM",
      cue_image: "img/Baer1.jpg",
      target_image: "img/Dachs5.jpg",
      cue_word: "img/BaerCC.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zwiebel",
      target: "Suppe",
      cond: "SEM",
      cue_image: "img/Zwiebel1.jpg",
      target_image: "img/Suppe5.jpg",
      cue_word: "img/ZwiebelCC.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Huhn",
      target: "Strassenbahn",
      cond: "NONE",
      cue_image: "img/Huhn2.jpg",
      target_image: "img/Strassenbahn5.jpg",
      cue_word: "img/HuhnCS.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kaffee",
      target: "Kaffee",
      cond: "IDEN",
      cue_image: "img/Kaffee2.jpg",
      target_image: "img/Kaffee5.jpg",
      cue_word: "img/KaffeeCS.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schraube",
      target: "Traube",
      cond: "PHON",
      cue_image: "img/Schraube2.jpg",
      target_image: "img/Traube5.jpg",
      cue_word: "img/SchraubeCS.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Lauch",
      target: "Lauch",
      cond: "IDEN",
      cue_image: "img/Lauch2.jpg",
      target_image: "img/Lauch6.jpg",
      cue_word: "img/LauchCS.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Apfel",
      target: "Traube",
      cond: "SEM",
      cue_image: "img/Apfel2.jpg",
      target_image: "img/Traube6.jpg",
      cue_word: "img/ApfelCS.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Stiefel",
      target: "Tasche",
      cond: "SEM",
      cue_image: "img/Stiefel2.jpg",
      target_image: "img/Tasche6.jpg",
      cue_word: "img/StiefelCS.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wachs",
      target: "Dachs",
      cond: "PHON",
      cue_image: "img/Wachs2.jpg",
      target_image: "img/Dachs6.jpg",
      cue_word: "img/WachsCS.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Milch",
      target: "Kaffee",
      cond: "SEM",
      cue_image: "img/Milch2.jpg",
      target_image: "img/Kaffee6.jpg",
      cue_word: "img/MilchCS.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hubschrauber",
      target: "Rakete",
      cond: "SEM",
      cue_image: "img/Hubschrauber1.jpg",
      target_image: "img/Rakete6.jpg",
      cue_word: "img/HubschrauberCC.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Eis",
      target: "Reis",
      cond: "PHON",
      cue_image: "img/Eis1.jpg",
      target_image: "img/Reis6.jpg",
      cue_word: "img/EisCC.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bus",
      target: "Strassenbahn",
      cond: "SEM",
      cue_image: "img/Bus1.jpg",
      target_image: "img/Strassenbahn6.jpg",
      cue_word: "img/BusCC.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schiff",
      target: "Lauch",
      cond: "NONE",
      cue_image: "img/Schiff2.jpg",
      target_image: "img/Lauch7.jpg",
      cue_word: "img/SchiffCS.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wal",
      target: "Wal",
      cond: "IDEN",
      cue_image: "img/Wal1.jpg",
      target_image: "img/Wal6.jpg",
      cue_word: "img/WalCC.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Ziege",
      target: "Schwein",
      cond: "SEM",
      cue_image: "img/Ziege2.jpg",
      target_image: "img/Schwein6.jpg",
      cue_word: "img/ZiegeCS.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Affe",
      target: "Flugzeug",
      cond: "NONE",
      cue_image: "img/Affe2.jpg",
      target_image: "img/Flugzeug6.jpg",
      cue_word: "img/AffeCS.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hut",
      target: "Kaffee",
      cond: "NONE",
      cue_image: "img/Hut1.jpg",
      target_image: "img/Kaffee7.jpg",
      cue_word: "img/HutCC.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hubschrauber",
      target: "Rakete",
      cond: "SEM",
      cue_image: "img/Hubschrauber2.jpg",
      target_image: "img/Rakete7.jpg",
      cue_word: "img/HubschrauberCS.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Baer",
      target: "Dachs",
      cond: "SEM",
      cue_image: "img/Baer2.jpg",
      target_image: "img/Dachs7.jpg",
      cue_word: "img/BaerCS.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hirsch",
      target: "Pferd",
      cond: "SEM",
      cue_image: "img/Hirsch1.jpg",
      target_image: "img/Pferd6.jpg",
      cue_word: "img/HirschCC.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kohl",
      target: "Lauch",
      cond: "SEM",
      cue_image: "img/Kohl2.jpg",
      target_image: "img/Lauch8.jpg",
      cue_word: "img/KohlCS.jpg",
      target_word: "img/LauchCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wal",
      target: "Wal",
      cond: "IDEN",
      cue_image: "img/Wal2.jpg",
      target_image: "img/Wal7.jpg",
      cue_word: "img/WalCS.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Suppe",
      target: "Suppe",
      cond: "IDEN",
      cue_image: "img/Suppe1.jpg",
      target_image: "img/Suppe6.jpg",
      cue_word: "img/SuppeCC.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pantoffel",
      target: "Kartoffel",
      cond: "PHON",
      cue_image: "img/Pantoffel2.jpg",
      target_image: "img/Kartoffel6.jpg",
      cue_word: "img/PantoffelCS.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bein",
      target: "Wein",
      cond: "PHON",
      cue_image: "img/Bein1.jpg",
      target_image: "img/Wein6.jpg",
      cue_word: "img/BeinCC.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Strassenbahn",
      target: "Strassenbahn",
      cond: "IDEN",
      cue_image: "img/Strassenbahn2.jpg",
      target_image: "img/Strassenbahn7.jpg",
      cue_word: "img/StrassenbahnCS.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hemd",
      target: "Knopf",
      cond: "SEM",
      cue_image: "img/Hemd1.jpg",
      target_image: "img/Knopf6.jpg",
      cue_word: "img/HemdCC.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Eis",
      target: "Reis",
      cond: "PHON",
      cue_image: "img/Eis2.jpg",
      target_image: "img/Reis7.jpg",
      cue_word: "img/EisCS.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Lauch",
      target: "Lauch",
      cond: "IDEN",
      cue_image: "img/Lauch3.jpg",
      target_image: "img/Lauch3.jpg",
      cue_word: "img/LauchTC.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Ballon",
      target: "Flugzeug",
      cond: "SEM",
      cue_image: "img/Ballon2.jpg",
      target_image: "img/Flugzeug7.jpg",
      cue_word: "img/BallonCS.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hund",
      target: "Fisch",
      cond: "SEM",
      cue_image: "img/Hund2.jpg",
      target_image: "img/Fisch6.jpg",
      cue_word: "img/HundCS.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bier",
      target: "Tee",
      cond: "SEM",
      cue_image: "img/Bier2.jpg",
      target_image: "img/Tee6.jpg",
      cue_word: "img/BierCS.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kamm",
      target: "Dachs",
      cond: "NONE",
      cue_image: "img/Kamm2.jpg",
      target_image: "img/Dachs8.jpg",
      cue_word: "img/KammCS.jpg",
      target_word: "img/DachsCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Tapete",
      target: "Rakete",
      cond: "PHON",
      cue_image: "img/Tapete2.jpg",
      target_image: "img/Rakete8.jpg",
      cue_word: "img/TapeteCS.jpg",
      target_word: "img/RaketeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Gras",
      target: "Knopf",
      cond: "NONE",
      cue_image: "img/Gras2.jpg",
      target_image: "img/Knopf7.jpg",
      cue_word: "img/GrasCS.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kartoffel",
      target: "Kartoffel",
      cond: "IDEN",
      cue_image: "img/Kartoffel2.jpg",
      target_image: "img/Kartoffel7.jpg",
      cue_word: "img/KartoffelCS.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schornstein",
      target: "Schwein",
      cond: "PHON",
      cue_image: "img/Schornstein2.jpg",
      target_image: "img/Schwein7.jpg",
      cue_word: "img/SchornsteinCS.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hose",
      target: "Hose",
      cond: "IDEN",
      cue_image: "img/Hose2.jpg",
      target_image: "img/Hose6.jpg",
      cue_word: "img/HoseCS.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bus",
      target: "Strassenbahn",
      cond: "SEM",
      cue_image: "img/Bus2.jpg",
      target_image: "img/Strassenbahn8.jpg",
      cue_word: "img/BusCS.jpg",
      target_word: "img/StrassenbahnCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kohl",
      target: "Lauch",
      cond: "SEM",
      cue_image: "img/Kohl3.jpg",
      target_image: "img/Lauch3.jpg",
      cue_word: "img/KohlTC.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hut",
      target: "Kaffee",
      cond: "NONE",
      cue_image: "img/Hut2.jpg",
      target_image: "img/Kaffee8.jpg",
      cue_word: "img/HutCS.jpg",
      target_word: "img/KaffeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Flugzeug",
      target: "Flugzeug",
      cond: "IDEN",
      cue_image: "img/Flugzeug2.jpg",
      target_image: "img/Flugzeug8.jpg",
      cue_word: "img/FlugzeugCS.jpg",
      target_word: "img/FlugzeugCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hemd",
      target: "Knopf",
      cond: "SEM",
      cue_image: "img/Hemd2.jpg",
      target_image: "img/Knopf8.jpg",
      cue_word: "img/HemdCS.jpg",
      target_word: "img/KnopfCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schnitzel",
      target: "Kartoffel",
      cond: "SEM",
      cue_image: "img/Schnitzel2.jpg",
      target_image: "img/Kartoffel8.jpg",
      cue_word: "img/SchnitzelCS.jpg",
      target_word: "img/KartoffelCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pferd",
      target: "Pferd",
      cond: "IDEN",
      cue_image: "img/Pferd2.jpg",
      target_image: "img/Pferd7.jpg",
      cue_word: "img/PferdCS.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Anzug",
      target: "Hose",
      cond: "SEM",
      cue_image: "img/Anzug2.jpg",
      target_image: "img/Hose7.jpg",
      cue_word: "img/AnzugCS.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schwan",
      target: "Strassenbahn",
      cond: "PHON",
      cue_image: "img/Schwan3.jpg",
      target_image: "img/Strassenbahn3.jpg",
      cue_word: "img/SchwanTC.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Maus",
      target: "Tee",
      cond: "NONE",
      cue_image: "img/Maus1.jpg",
      target_image: "img/Tee7.jpg",
      cue_word: "img/MausCC.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fussball",
      target: "Traube",
      cond: "NONE",
      cue_image: "img/Fussball1.jpg",
      target_image: "img/Traube7.jpg",
      cue_word: "img/FussballCC.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Loeffel",
      target: "Tasche",
      cond: "NONE",
      cue_image: "img/Loeffel2.jpg",
      target_image: "img/Tasche7.jpg",
      cue_word: "img/LoeffelCS.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hemd",
      target: "Knopf",
      cond: "SEM",
      cue_image: "img/Hemd3.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/HemdTC.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schlagzeug",
      target: "Flugzeug",
      cond: "PHON",
      cue_image: "img/Schlagzeug3.jpg",
      target_image: "img/Flugzeug3.jpg",
      cue_word: "img/SchlagzeugTC.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Tapete",
      target: "Rakete",
      cond: "PHON",
      cue_image: "img/Tapete3.jpg",
      target_image: "img/Rakete3.jpg",
      cue_word: "img/TapeteTC.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Brot",
      target: "Fisch",
      cond: "NONE",
      cue_image: "img/Brot2.jpg",
      target_image: "img/Fisch7.jpg",
      cue_word: "img/BrotCS.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bus",
      target: "Strassenbahn",
      cond: "SEM",
      cue_image: "img/Bus3.jpg",
      target_image: "img/Strassenbahn3.jpg",
      cue_word: "img/BusTC.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kuh",
      target: "Schuh",
      cond: "PHON",
      cue_image: "img/Kuh2.jpg",
      target_image: "img/Schuh6.jpg",
      cue_word: "img/KuhCS.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Suppe",
      target: "Suppe",
      cond: "IDEN",
      cue_image: "img/Suppe2.jpg",
      target_image: "img/Suppe7.jpg",
      cue_word: "img/SuppeCS.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pedal",
      target: "Wal",
      cond: "PHON",
      cue_image: "img/Pedal2.jpg",
      target_image: "img/Wal8.jpg",
      cue_word: "img/PedalCS.jpg",
      target_word: "img/WalCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bauch",
      target: "Lauch",
      cond: "PHON",
      cue_image: "img/Bauch3.jpg",
      target_image: "img/Lauch3.jpg",
      cue_word: "img/BauchTC.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Dachs",
      target: "Dachs",
      cond: "IDEN",
      cue_image: "img/Dachs3.jpg",
      target_image: "img/Dachs3.jpg",
      cue_word: "img/DachsTC.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Knopf",
      target: "Knopf",
      cond: "IDEN",
      cue_image: "img/Knopf3.jpg",
      target_image: "img/Knopf3.jpg",
      cue_word: "img/KnopfTC.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fisch",
      target: "Fisch",
      cond: "IDEN",
      cue_image: "img/Fisch2.jpg",
      target_image: "img/Fisch8.jpg",
      cue_word: "img/FischCS.jpg",
      target_word: "img/FischCS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Rakete",
      target: "Rakete",
      cond: "IDEN",
      cue_image: "img/Rakete3.jpg",
      target_image: "img/Rakete3.jpg",
      cue_word: "img/RaketeTC.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Nest",
      target: "Schuh",
      cond: "NONE",
      cue_image: "img/Nest1.jpg",
      target_image: "img/Schuh7.jpg",
      cue_word: "img/NestCC.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Flasche",
      target: "Tasche",
      cond: "PHON",
      cue_image: "img/Flasche2.jpg",
      target_image: "img/Tasche8.jpg",
      cue_word: "img/FlascheCS.jpg",
      target_word: "img/TascheCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schnee",
      target: "Kaffee",
      cond: "PHON",
      cue_image: "img/Schnee3.jpg",
      target_image: "img/Kaffee3.jpg",
      cue_word: "img/SchneeTC.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Mehl",
      target: "Reis",
      cond: "SEM",
      cue_image: "img/Mehl2.jpg",
      target_image: "img/Reis8.jpg",
      cue_word: "img/MehlCS.jpg",
      target_word: "img/ReisCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Rose",
      target: "Hose",
      cond: "PHON",
      cue_image: "img/Rose2.jpg",
      target_image: "img/Hose8.jpg",
      cue_word: "img/RoseCS.jpg",
      target_word: "img/HoseCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Zwiebel",
      target: "Suppe",
      cond: "SEM",
      cue_image: "img/Zwiebel2.jpg",
      target_image: "img/Suppe8.jpg",
      cue_word: "img/ZwiebelCS.jpg",
      target_word: "img/SuppeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bein",
      target: "Wein",
      cond: "PHON",
      cue_image: "img/Bein2.jpg",
      target_image: "img/Wein7.jpg",
      cue_word: "img/BeinCS.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Knopf",
      target: "Knopf",
      cond: "IDEN",
      cue_image: "img/Knopf4.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/KnopfTS.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wal",
      target: "Wal",
      cond: "IDEN",
      cue_image: "img/Wal3.jpg",
      target_image: "img/Wal3.jpg",
      cue_word: "img/WalTC.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fussball",
      target: "Traube",
      cond: "NONE",
      cue_image: "img/Fussball2.jpg",
      target_image: "img/Traube8.jpg",
      cue_word: "img/FussballCS.jpg",
      target_word: "img/TraubeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kartoffel",
      target: "Kartoffel",
      cond: "IDEN",
      cue_image: "img/Kartoffel3.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/KartoffelTC.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Stiefel",
      target: "Tasche",
      cond: "SEM",
      cue_image: "img/Stiefel3.jpg",
      target_image: "img/Tasche3.jpg",
      cue_word: "img/StiefelTC.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Anzug",
      target: "Hose",
      cond: "SEM",
      cue_image: "img/Anzug3.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/AnzugTC.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Brot",
      target: "Fisch",
      cond: "NONE",
      cue_image: "img/Brot3.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/BrotTC.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Zelt",
      target: "Wein",
      cond: "NONE",
      cue_image: "img/Zelt2.jpg",
      target_image: "img/Wein8.jpg",
      cue_word: "img/ZeltCS.jpg",
      target_word: "img/WeinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Elefant",
      target: "Rakete",
      cond: "NONE",
      cue_image: "img/Elefant3.jpg",
      target_image: "img/Rakete3.jpg",
      cue_word: "img/ElefantTC.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Nest",
      target: "Schuh",
      cond: "NONE",
      cue_image: "img/Nest2.jpg",
      target_image: "img/Schuh8.jpg",
      cue_word: "img/NestCS.jpg",
      target_word: "img/SchuhCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hammer",
      target: "Suppe",
      cond: "NONE",
      cue_image: "img/Hammer3.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/HammerTC.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schraube",
      target: "Traube",
      cond: "PHON",
      cue_image: "img/Schraube3.jpg",
      target_image: "img/Traube3.jpg",
      cue_word: "img/SchraubeTC.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Tasche",
      target: "Tasche",
      cond: "IDEN",
      cue_image: "img/Tasche3.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/TascheTC.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hose",
      target: "Hose",
      cond: "IDEN",
      cue_image: "img/Hose3.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/HoseTC.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Tisch",
      target: "Fisch",
      cond: "PHON",
      cue_image: "img/Tisch3.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/TischTC.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Zelt",
      target: "Wein",
      cond: "NONE",
      cue_image: "img/Zelt3.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/ZeltTC.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pfanne",
      target: "Schwein",
      cond: "NONE",
      cue_image: "img/Pfanne2.jpg",
      target_image: "img/Schwein8.jpg",
      cue_word: "img/PfanneCS.jpg",
      target_word: "img/SchweinCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Maus",
      target: "Tee",
      cond: "NONE",
      cue_image: "img/Maus2.jpg",
      target_image: "img/Tee8.jpg",
      cue_word: "img/MausCS.jpg",
      target_word: "img/TeeCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Gurke",
      target: "Wal",
      cond: "NONE",
      cue_image: "img/Gurke3.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/GurkeTC.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schnee",
      target: "Kaffee",
      cond: "PHON",
      cue_image: "img/Schnee4.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/SchneeTS.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kartoffel",
      target: "Kartoffel",
      cond: "IDEN",
      cue_image: "img/Kartoffel4.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/KartoffelTS.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Rose",
      target: "Hose",
      cond: "PHON",
      cue_image: "img/Rose3.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/RoseTC.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fisch",
      target: "Fisch",
      cond: "IDEN",
      cue_image: "img/Fisch3.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/FischTC.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wein",
      target: "Wein",
      cond: "IDEN",
      cue_image: "img/Wein3.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/WeinTC.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schwein",
      target: "Schwein",
      cond: "IDEN",
      cue_image: "img/Schwein3.jpg",
      target_image: "img/Schwein3.jpg",
      cue_word: "img/SchweinTC.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hirsch",
      target: "Pferd",
      cond: "SEM",
      cue_image: "img/Hirsch2.jpg",
      target_image: "img/Pferd8.jpg",
      cue_word: "img/HirschCS.jpg",
      target_word: "img/PferdCS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kuh",
      target: "Schuh",
      cond: "PHON",
      cue_image: "img/Kuh3.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/KuhTC.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hut",
      target: "Kaffee",
      cond: "NONE",
      cue_image: "img/Hut3.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/HutTC.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Puppe",
      target: "Suppe",
      cond: "PHON",
      cue_image: "img/Puppe3.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/PuppeTC.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Loeffel",
      target: "Tasche",
      cond: "NONE",
      cue_image: "img/Loeffel3.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/LoeffelTC.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wal",
      target: "Wal",
      cond: "IDEN",
      cue_image: "img/Wal4.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/WalTS.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Apfel",
      target: "Traube",
      cond: "SEM",
      cue_image: "img/Apfel3.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/ApfelTC.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schornstein",
      target: "Schwein",
      cond: "PHON",
      cue_image: "img/Schornstein3.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/SchornsteinTC.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schwan",
      target: "Strassenbahn",
      cond: "PHON",
      cue_image: "img/Schwan4.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/SchwanTS.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schwert",
      target: "Pferd",
      cond: "PHON",
      cue_image: "img/Schwert3.jpg",
      target_image: "img/Pferd3.jpg",
      cue_word: "img/SchwertTC.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Nest",
      target: "Schuh",
      cond: "NONE",
      cue_image: "img/Nest3.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/NestTC.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Horn",
      target: "Reis",
      cond: "NONE",
      cue_image: "img/Horn3.jpg",
      target_image: "img/Reis3.jpg",
      cue_word: "img/HornTC.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Puppe",
      target: "Suppe",
      cond: "PHON",
      cue_image: "img/Puppe4.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/PuppeTS.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kohl",
      target: "Lauch",
      cond: "SEM",
      cue_image: "img/Kohl4.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/KohlTS.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Traube",
      target: "Traube",
      cond: "IDEN",
      cue_image: "img/Traube3.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/TraubeTC.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schwein",
      target: "Schwein",
      cond: "IDEN",
      cue_image: "img/Schwein4.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/SchweinTS.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Affe",
      target: "Flugzeug",
      cond: "NONE",
      cue_image: "img/Affe3.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/AffeTC.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hirsch",
      target: "Pferd",
      cond: "SEM",
      cue_image: "img/Hirsch3.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/HirschTC.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kleid",
      target: "Schuh",
      cond: "SEM",
      cue_image: "img/Kleid3.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/KleidTC.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Reis",
      target: "Reis",
      cond: "IDEN",
      cue_image: "img/Reis3.jpg",
      target_image: "img/Reis3.jpg",
      cue_word: "img/ReisTC.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Bier",
      target: "Tee",
      cond: "SEM",
      cue_image: "img/Bier3.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/BierTC.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schnitzel",
      target: "Kartoffel",
      cond: "SEM",
      cue_image: "img/Schnitzel3.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/SchnitzelTC.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Baer",
      target: "Dachs",
      cond: "SEM",
      cue_image: "img/Baer3.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/BaerTC.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hose",
      target: "Hose",
      cond: "IDEN",
      cue_image: "img/Hose4.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/HoseTS.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Wein",
      target: "Wein",
      cond: "IDEN",
      cue_image: "img/Wein4.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/WeinTS.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pferd",
      target: "Pferd",
      cond: "IDEN",
      cue_image: "img/Pferd3.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/PferdTC.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kaffee",
      target: "Kaffee",
      cond: "IDEN",
      cue_image: "img/Kaffee3.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/KaffeeTC.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Horn",
      target: "Reis",
      cond: "NONE",
      cue_image: "img/Horn4.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/HornTS.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Tee",
      target: "Tee",
      cond: "IDEN",
      cue_image: "img/Tee3.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/TeeTC.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kuh",
      target: "Schuh",
      cond: "PHON",
      cue_image: "img/Kuh4.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/KuhTS.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pantoffel",
      target: "Kartoffel",
      cond: "PHON",
      cue_image: "img/Pantoffel3.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/PantoffelTC.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Rose",
      target: "Hose",
      cond: "PHON",
      cue_image: "img/Rose4.jpg",
      target_image: "img/Hose4.jpg",
      cue_word: "img/RoseTS.jpg",
      target_word: "img/HoseTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Gurke",
      target: "Wal",
      cond: "NONE",
      cue_image: "img/Gurke4.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/GurkeTS.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Pferd",
      target: "Pferd",
      cond: "IDEN",
      cue_image: "img/Pferd4.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/PferdTS.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schiff",
      target: "Lauch",
      cond: "NONE",
      cue_image: "img/Schiff3.jpg",
      target_image: "img/Lauch4.jpg",
      cue_word: "img/SchiffTC.jpg",
      target_word: "img/LauchTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Kaffee",
      target: "Kaffee",
      cond: "IDEN",
      cue_image: "img/Kaffee4.jpg",
      target_image: "img/Kaffee4.jpg",
      cue_word: "img/KaffeeTS.jpg",
      target_word: "img/KaffeeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Ziege",
      target: "Schwein",
      cond: "SEM",
      cue_image: "img/Ziege3.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/ZiegeTC.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fussball",
      target: "Traube",
      cond: "NONE",
      cue_image: "img/Fussball3.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/FussballTC.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Schnitzel",
      target: "Kartoffel",
      cond: "SEM",
      cue_image: "img/Schnitzel4.jpg",
      target_image: "img/Kartoffel4.jpg",
      cue_word: "img/SchnitzelTS.jpg",
      target_word: "img/KartoffelTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Maus",
      target: "Tee",
      cond: "NONE",
      cue_image: "img/Maus3.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/MausTC.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Flugzeug",
      target: "Flugzeug",
      cond: "IDEN",
      cue_image: "img/Flugzeug3.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/FlugzeugTC.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Stiefel",
      target: "Tasche",
      cond: "SEM",
      cue_image: "img/Stiefel4.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/StiefelTS.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Zahn",
      target: "Pferd",
      cond: "NONE",
      cue_image: "img/Zahn3.jpg",
      target_image: "img/Pferd4.jpg",
      cue_word: "img/ZahnTC.jpg",
      target_word: "img/PferdTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Suppe",
      target: "Suppe",
      cond: "IDEN",
      cue_image: "img/Suppe3.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/SuppeTC.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "m",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hund",
      target: "Fisch",
      cond: "SEM",
      cue_image: "img/Hund3.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/HundTC.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kamm",
      target: "Dachs",
      cond: "NONE",
      cue_image: "img/Kamm3.jpg",
      target_image: "img/Dachs3.jpg",
      cue_word: "img/KammTC.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Fussball",
      target: "Traube",
      cond: "NONE",
      cue_image: "img/Fussball4.jpg",
      target_image: "img/Traube4.jpg",
      cue_word: "img/FussballTS.jpg",
      target_word: "img/TraubeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Mehl",
      target: "Reis",
      cond: "SEM",
      cue_image: "img/Mehl3.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/MehlTC.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Kleid",
      target: "Schuh",
      cond: "SEM",
      cue_image: "img/Kleid4.jpg",
      target_image: "img/Schuh4.jpg",
      cue_word: "img/KleidTS.jpg",
      target_word: "img/SchuhTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Maus",
      target: "Tee",
      cond: "NONE",
      cue_image: "img/Maus4.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/MausTS.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Ballon",
      target: "Flugzeug",
      cond: "SEM",
      cue_image: "img/Ballon3.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/BallonTC.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Gras",
      target: "Knopf",
      cond: "NONE",
      cue_image: "img/Gras3.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/GrasTC.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Flasche",
      target: "Tasche",
      cond: "PHON",
      cue_image: "img/Flasche3.jpg",
      target_image: "img/Tasche4.jpg",
      cue_word: "img/FlascheTC.jpg",
      target_word: "img/TascheTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Zwiebel",
      target: "Suppe",
      cond: "SEM",
      cue_image: "img/Zwiebel3.jpg",
      target_image: "img/Suppe4.jpg",
      cue_word: "img/ZwiebelTC.jpg",
      target_word: "img/SuppeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Wachs",
      target: "Dachs",
      cond: "PHON",
      cue_image: "img/Wachs3.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/WachsTC.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Zelt",
      target: "Wein",
      cond: "NONE",
      cue_image: "img/Zelt4.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/ZeltTS.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Elefant",
      target: "Rakete",
      cond: "NONE",
      cue_image: "img/Elefant4.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/ElefantTS.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Hund",
      target: "Fisch",
      cond: "SEM",
      cue_image: "img/Hund4.jpg",
      target_image: "img/Fisch4.jpg",
      cue_word: "img/HundTS.jpg",
      target_word: "img/FischTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Schlagzeug",
      target: "Flugzeug",
      cond: "PHON",
      cue_image: "img/Schlagzeug4.jpg",
      target_image: "img/Flugzeug4.jpg",
      cue_word: "img/SchlagzeugTS.jpg",
      target_word: "img/FlugzeugTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Huhn",
      target: "Strassenbahn",
      cond: "NONE",
      cue_image: "img/Huhn3.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/HuhnTC.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "word-pic"
    },
    {
      cue: "Ziege",
      target: "Schwein",
      cond: "SEM",
      cue_image: "img/Ziege4.jpg",
      target_image: "img/Schwein4.jpg",
      cue_word: "img/ZiegeTS.jpg",
      target_word: "img/SchweinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Gras",
      target: "Knopf",
      cond: "NONE",
      cue_image: "img/Gras4.jpg",
      target_image: "img/Knopf4.jpg",
      cue_word: "img/GrasTS.jpg",
      target_word: "img/KnopfTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Eis",
      target: "Reis",
      cond: "PHON",
      cue_image: "img/Eis3.jpg",
      target_image: "img/Reis4.jpg",
      cue_word: "img/EisTC.jpg",
      target_word: "img/ReisTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Pedal",
      target: "Wal",
      cond: "PHON",
      cue_image: "img/Pedal3.jpg",
      target_image: "img/Wal4.jpg",
      cue_word: "img/PedalTC.jpg",
      target_word: "img/WalTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Hubschrauber",
      target: "Rakete",
      cond: "SEM",
      cue_image: "img/Hubschrauber3.jpg",
      target_image: "img/Rakete4.jpg",
      cue_word: "img/HubschrauberTC.jpg",
      target_word: "img/RaketeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Saft",
      target: "Wein",
      cond: "SEM",
      cue_image: "img/Saft3.jpg",
      target_image: "img/Wein4.jpg",
      cue_word: "img/SaftTC.jpg",
      target_word: "img/WeinTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Klee",
      target: "Tee",
      cond: "PHON",
      cue_image: "img/Klee3.jpg",
      target_image: "img/Tee4.jpg",
      cue_word: "img/KleeTC.jpg",
      target_word: "img/TeeTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Bus",
      target: "Strassenbahn",
      cond: "SEM",
      cue_image: "img/Bus4.jpg",
      target_image: "img/Strassenbahn4.jpg",
      cue_word: "img/BusTS.jpg",
      target_word: "img/StrassenbahnTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    },
    {
      cue: "Baer",
      target: "Dachs",
      cond: "SEM",
      cue_image: "img/Baer4.jpg",
      target_image: "img/Dachs4.jpg",
      cue_word: "img/BaerTS.jpg",
      target_word: "img/DachsTS.jpg",
      correct_resp: "n",
      trial_part: "main",
      pic_word_con: "pic-word"
    }
  ]